.\" Manpage for fspcc.
.\" Contact v.maffione@gmail.com to correct errors or typos.
.TH "FSPCC" "1" "June 2013" "fspcc 1.1" "fspcc manual"

.SH NAME
fspcc \- An FSP compiler and LTS analysis tool

.SH SYNOPSIS
.B fspcc
[\fI-dpgasSh\fR] \fI-i FILE\fR [\fI-o FILE\fR]
.br
.B fspcc
[\fI-dpgasSh\fR] \fI-l FILE\fR


.SH DESCRIPTION
.PP
This command invokes an Finite State Process (FSP) compiler and a
Labelled Transition System (LTS) analysis tool.
.PP
The FSP language can be used to model concurrent systems, e.g.
multi-threaded/multi-process applications. An FSP model can be
compiled into a graph-based representation using an FSP compiler:
each FSP process is transformed into an equivalent LTS.
.PP
An LTS analysis tool is then able to:
.RS 3
.IP "   -"
detect concurrency problems in the concurrent system (e.g. deadlock,
starvation)
.RE
.RS 3
.IP "   -"
show that certain properties (or assertions) hold on the concurrent system
.RE
.RS 3
.IP "   -"
run a simulation (animation) of the concurrent system, in order to gain
confidence on the model
.RE
.PP
When invoked in the first form, you use the \fI-i\fR option to specify an
input file containing FSP definitions. The tool will compile all the FSP
models and produce an output file containing the corresponding compiled LTSs.
.PP
When invoked in the second form, you use the \fI-l\fR option to specify a
file containing a set of compiled LTSs, in order to use the LTS analysis
tool without compiling again.


.SH OPTIONS
.PP
\fB\-i\fR \fIPATHNAME\fR
.RS 3
Specifies an input file pathname containing FSP definitions to compile.
.RE
.PP
\fB\-o\fR \fIPATHNAME\fR
.RS 3
Specifies the output file pathname where compiled LTSs are stored.
.RE
.PP
\fB\-l\fR \fIPATHNAME\fR
.RS 3
Specifies the input file pathname containing compiled LTSs.
.RE
.PP
\fB\-d\fR
.RS 3
Runs deadlock/error analysis on every compiled LTS.
.RE
.PP
\fB\-p\fR
.RS 3
Runs all the specified progress checks on every compiled LTS.
.RE
.PP
\fB\-g\fR
.RS 3
Outputs a GraphViz representation file corrisponding to every LTS.
.RE
.PP
\fB\-a\fR
.RS 3
The same as \fB\-dpg\fR.
.RE
.PP
\fB\-s\fR
.RS 3
Runs an LTS analysis interactive shell. The shell is run after compilation
(if any).
.RE
.PP
\fB\-S\fR \fIPATHNAME\fR
.RS 3
Runs the LTS analysis script specified by the pathname. The script is
run after the compilation (if any) but before invoking the interactive shell
(when \fB\-s\fR is specified).
.RE


.SH AUTHOR
Written by Vincenzo Maffione.

.SH REPORTING BUGS
Please report fspcc bugs to v.maffione@gmail.com.
.br
See fspcc project homepage: <http://www.bitbucket.org/vmaffione/fspc>

.SH COPYRIGHT
Copyright \(co 2013 Vincenzo Maffione.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
\fBgraphviz\fR(7), \fBdot\fR(1)
