#!/bin/bash

#set -x

if [ "$1" == "" ]; then
    echo "USAGE: ltsee P.gv"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "$1: no such file"
    exit 1
fi

#check if we have the dot command
which dot &> /dev/null
if [ "$?" != "0" ]; then
    echo "\"dot\" program not found"
    echo "Try to install the graphviz package"
    exit 1
fi

#check if we have the xv command
which xv &> /dev/null
if [ "$?" != "0" ]; then
    echo "\"xv\" program not found"
    exit 1
fi

dot -Tpng $1 -o ".$1.png"
xv ".$1.png"
rm ".$1.png"

